### ISSUE TITLE
discussion

### ISSUE THREAD

**Issue by szymor** [Apaczer/chadtalk#1]
If I understand correctly, you wanted to play around with a few LLMs to generate some code.

From my perspective, the best solution would be to use aider (check at aider.chat) as it is tightly integrated with git and enriches user prompt with repository map and some additional context. You can take a look of an example project of mine here:

https://github.com/szymor/polduino-welcome

Enjoy :)

**Comment by Apaczer** [comment]
Tks 👍, I guess `llama3:70b` would be the easiest choice for local tests and free api? I mostly use web chats to generate "complex" `sed` cmds/loops and for single compilation src (like so in here).

**Comment by szymor** [comment]
I guess so. It is on LLM leaderboard of aider so it is usable but still much worse than gpt4o, which is far from ideal tbh.
